### ISSUE TITLE
No Docker image available for this engine

### ISSUE THREAD

**Issue by sgerrand** [andrewhr/codeclimate-kibit#1]
No Docker image is available for this engine on [Docker Hub](https://hub.docker.com), which prevents it from being used for Clojure projects in Code Climate. :crying_cat_face:

Is this intentional? If not, is there a timeframe for publishing the image?

CC: @mrb

**Comment by gdiggs** [comment]
@sgerrand @mrb @andrewhr I have pushed this image up to Docker Hub! https://hub.docker.com/r/codeclimate/codeclimate-kibit/

**Comment by sgerrand** [comment]
(Belated) thanks!

**Comment by andrewhr** [comment]
thanks @sgerrand and @GordonDiggs !
