### ISSUE TITLE
Invalid engine output 

### ISSUE THREAD

**Issue by ABaldwinHunter** [andrewhr/codeclimate-kibit#3]
When the native Kibit tool encounters an exception in analyzing a particular file, it outputs [this message](https://github.com/jonase/kibit/blob/master/src/kibit/driver.clj#L43) to STDOUT:

```
(println "Check failed -- skipping rest of file")
```

which causes the engine analysis to fail.

**Example**

On codeclimate.com it manifests as [invalid issue output](https://codeclimate.com/github/ABaldwinHunter/overtone/builds/1) with line numbers being `nil`.

In the CLI, the error appears as a JSON parse issue and its root is more apparent:

``````
$ codeclimate analyze -e kibit

Running kibit: Done!
error: (JSON::ParserError) 757: unexpected token at 'Check failed -- skipping rest of file
java.lang.RuntimeException: Unsupported character: \default
{"type":"issue","check_name":"kibit/suggestion","description":"Non-idiomatic code found in 
`apply`","categories":["Style"],"location":{"path":"src/overtone/config/log.clj","lines":
{"begin":72,"end":72}},"content":{"body":"<p>Consider using:</p><pre>```(clojure.string/join 
msg)```</pre><p>instead of:</p><pre>```(apply str msg)```</pre>"},"remediation_points":50000}'
``````

**Desired behavior**

Reroute the `skipping rest of file` message to STDERR, as we do for some rescuable errors in other engines, e.g. [codeclimate-duplication](https://github.com/codeclimate/codeclimate-duplication/blob/master/lib/cc/engine/analyzers/analyzer_base.rb#L26). These will still be visible to user in the UI, but permit analysis to continue - as it does when running `lein kibit` natively. 

**Ideas for fixing**

I believe that the `nil` line numbers are a secondary effect from the analysis dying as a result of the exception message, not a cause, but we could still add a `line: (or line 1)` guard.

Looking at the native tool, I'm not sure the best way to prevent that output from escaping the engine.  **Some options**:
1. Implement change in a fork / native integration
2. Catch the stdout before rerouting 
3. Make a pull against the kibit project to add a `--quiet` flag that would suppress such output. Could be the most sustainable and useful. 

Look forward to hearing your thoughts!

**Comment by jpignata** [comment]
Hey @ABaldwinHunter – I opened a pull against kibit to redirect the output from the exception to STDERR which was just merged (https://github.com/jonase/kibit/pull/152). Once a new release is up, I'll open a pull against the engine to update it.

The line number and exception output are two distinct issues, so I have a pull opened on the engine to resolve the line number default separately (https://github.com/andrewhr/codeclimate-kibit/pull/4).

I think this issue can be closed.

**Comment by ABaldwinHunter** [comment]
@jpignata Thanks! Nice fix. Closing this issue.

**Comment by andrewhr** [comment]
Thanks @jpignata and @ABaldwinHunter for the report and fixes! :beers:
